Tencent-RTC/TUILiveKit

- Android/.gitignore
- Android/Source/src/main/java/com/tencent/liteav/basic/UserModel.java
- Android/Source/src/main/java/com/tencent/liteav/liveroom/model/impl/av/trtc/TXTRTCLiveRoom.java
> release-9.5.11200

- iOS/TUILiveRoomApp.xcodeproj/project.pbxproj
> [iOS] update version to relesse-9.5.0.1464

- iOS/TUILiveRoomApp.xcodeproj/project.pbxproj
> [iOS] update version to relesse-9.5.0.1477

- iOS/Podfile.lock
- iOS/README.md
1. 修改README.md
2. 更新Podfile.lock
> 【iOS】update README.md

- Android/README.md
> 【Android】README文件更新

- iOS/Example/App/Info.plist
- iOS/Example/TUILiveRoomApp.xcodeproj/project.pbxproj
- iOS/Source/ui/Anchor/TCAnchorViewController.swift
- iOS/Source/ui/Audience/TCAudienceToolbarView.swift
- iOS/TUIBarrage/Example/App/Info.plist
- iOS/TUIBeauty/Example/App/Info.plist
- iOS/TUIBeauty/Source/UI/TUIBeautyView.m
- iOS/TUIGift/Example/App/Info.plist
> [iOS] update version to relesse-10.2.0.2443

- iOS/Example/App/Info.plist
- iOS/Example/Podfile
- iOS/Example/TUILiveRoomApp.xcodeproj/project.pbxproj
- iOS/Source/model/Impl/TRTCLiveRoom.m
- iOS/Source/ui/Anchor/TCAnchorViewController.swift
- iOS/Source/ui/Audience/TCAudienceViewController.swift
- iOS/TUIBarrage/Example/App/Info.plist
- iOS/TUIBeauty/Example/App/Info.plist
- iOS/TUIGift/Example/App/Info.plist
> [iOS] update version to relesse-10.4.0.2632

- iOS/Example/Debug/GenerateTestUserSig.swift
> 【iOS】【TUILiveRoom】修改编译报错问题

- iOS/Example/App/Info.plist
- iOS/Example/TUILiveRoomApp.xcodeproj/project.pbxproj
- iOS/Source/model/Impl/trtc/TRTCCloudAnction.m
- iOS/TUIBarrage/Example/App/Info.plist
- iOS/TUIBeauty/Example/App/Info.plist
- iOS/TUIBeauty/Source/Presenter/TUIBeautyService.m
- iOS/TUIGift/Example/App/Info.plist
> [iOS] update version to relesse-10.8.0.3022

- Android/tuibarrage/src/main/java/com/tencent/qcloud/tuikit/tuibarrage/core/TUIBarrageExtension.java
- Android/tuibeauty/src/main/java/com/tencent/qcloud/tuikit/tuibeauty/core/TUIBeautyExtension.java
- Android/tuibeauty/src/main/java/com/tencent/qcloud/tuikit/tuibeauty/core/TUIBeautyProvider.java
- Android/tuibeauty/src/main/java/com/tencent/qcloud/tuikit/tuibeauty/model/TUIBeautyService.java
- Android/tuiliveroom/src/main/java/com/tencent/liteav/basic/Constants.java
- Android/tuiliveroom/src/main/java/com/tencent/liteav/liveroom/model/impl/TRTCLiveRoomImpl.java
- Android/tuiliveroom/src/main/java/com/tencent/liteav/liveroom/model/impl/room/impl/TXRoomService.java
- Android/tuiliveroom/src/main/java/com/tencent/liteav/liveroom/ui/common/utils/TCUtils.java
> release-10.8.13065

- Android/app/build.gradle
- Android/build.gradle
- Android/debug/build.gradle
- Android/gradle.properties
- Android/gradle/wrapper/gradle-wrapper.properties
- Android/tuilivekit/build.gradle
The default adaptation is gradle8.0 and above
> 【TUILiveKit】【Android】The default adaptation is gradle8.0 and above

- Android/app/src/main/java/com/trtc/uikit/livekit/example/view/main/MainActivity.java
Resource ID uses if else method instead of switch method
> 【TUILiveKit】【Android】Resource ID uses if else method instead of switch method

- README-zh_CN.md
- README.md
> 【TUILiveKit】【Android&iOS】Modify the readme file

- Android/tuilivekit/src/main/java/com/trtc/uikit/livekit/common/utils/GridLayoutHelper.java
- Android/tuilivekit/src/main/java/com/trtc/uikit/livekit/common/utils/LinkMicGridHelper.java
> 【TUILiveKit】【Android】repair exception

- Android/tuilivekit/src/main/java/com/trtc/uikit/livekit/manager/controller/SeatController.java
【TUILiveKit】【Android】Clear call logs after hang-up
> 【TUILiveKit】【Android】Clear call logs after hang-up

- iOS/CHANGELOG.md
- iOS/TUILiveKit/Source/Common/Log/LiveKitLog.swift
- iOS/TUILiveKit/Source/Common/UIComponent/LiveList/View/LiveListRootView.swift
- iOS/TUILiveKit/Source/Service/EngineServiceCenter.swift
- iOS/TUILiveKit/Source/Store/Room/RoomEffects.swift
- iOS/TUILiveKit/Source/View/LiveRoom/TUILiveRoomAnchorViewController.swift
- iOS/TUILiveKit/Source/View/TUILivePreviewViewController.swift
- iOS/TUILiveKit/Source/View/VoiceRoom/TUIVoiceRoomViewController.swift
- iOS/TUILiveKit/Source/View/VoiceRoom/View/Panel/AlertPanel.swift
- iOS/TUILiveKit/Source/View/VoiceRoom/View/Prepare/VoiceRoomPrepareView.swift
- iOS/TUILiveKit/Source/View/VoiceRoom/View/Root/VoiceRoomRootMenuDataCreator.swift
- iOS/TUILiveKit/Source/View/VoiceRoom/View/Root/VoiceRoomRootView.swift
- iOS/TUILiveKit/TUILiveKit.podspec
- Android&iOS: Add new feature for room owners change room background in voice rooms
- Android&iOS: Optimize some known issues
> 【TUILiveKit】【iOS】update 2.4.0 version

- iOS/TUILiveKit/Sources/Component/Gift/GiftPlayView.swift
- iOS/TUILiveKit/Sources/Component/Gift/View/Animation/AnimationView.swift
- iOS/TUILiveKit/Sources/Component/Gift/View/Animation/AnimationViewWrapper.swift
- iOS/TUILiveKit/Sources/Component/Gift/View/Animation/SVGAAnimationView.swift
- iOS/TUILiveKit/Sources/Component/Gift/View/Animation/TCEffectAnimationView.swift
- iOS/TUILiveKit/Sources/LiveStream/Main/API/LSRoomEngineService.swift
- iOS/TUILiveKit/Sources/LiveStream/Main/Manager/LiveStreamManager.swift
- iOS/TUILiveKit/Sources/LiveStream/Main/Manager/Module/LSRoomManager.swift
- iOS/TUILiveKit/Sources/LiveStream/Main/Manager/Module/LSUserManager.swift
- iOS/TUILiveKit/Sources/LiveStream/Main/View/Anchor/AnchorView.swift
- iOS/TUILiveKit/Sources/LiveStream/Main/View/Audience/AudienceView.swift
- iOS/TUILiveKit/Sources/LiveStream/Main/View/LiveRoomRootMenuDataCreator.swift
- iOS/TUILiveKit/Sources/LiveStream/TUILiveRoomAnchorViewController.swift
- iOS/TUILiveKit/TUILiveKit.podspec
【TUILiveKit】【iOS】Supports special effects playback of svga and mp4, and the host to directly set room information using code
> 【TUILiveKit】【iOS】Supports special effects playback of svga and mp4, and the host to directly set room information using code

- Android/livestreamcore/build.gradle
- Android/tuilivekit/build.gradle
- Android/voiceroomcore/build.gradle
Upgrade the common module version
> 【LiveKit】【Android】Upgrade the common module version

- Android/settings.gradle
- Android/tuilivekit/livekit/build.gradle
> 【LiveKit】【Android】【V2.8.0】fix aar problem

- iOS/SeatGridView/SeatGridView.podspec
- iOS/TUILiveKit/TUILiveKit.podspec
> 【TUILiveKit】【iOS】Remove Kingfisher third-party library version restrictions

- Android/tuilivekit/livekit/src/main/java/com/trtc/uikit/livekit/livestream/VideoLiveKit.java
- Android/tuilivekit/livekit/src/main/java/com/trtc/uikit/livekit/livestream/view/VideoLiveKitImpl.java
- Android/tuilivekit/livekit/src/main/java/com/trtc/uikit/livekit/livestream/view/anchor/VideoLiveAnchorActivity.java
- Android/tuilivekit/livekit/src/main/java/com/trtc/uikit/livekit/livestream/view/audience/VideoLiveAudienceActivity.java
> 【TUILiveKit】【Android】add leaveLive api

- iOS/TCEffectPlayerKit/Classes/TUIExtension/TCConstant.h
- iOS/TCEffectPlayerKit/Classes/TUIExtension/TUIEffectPlayerExtension.h
- iOS/TCEffectPlayerKit/Classes/TUIExtension/TUIEffectPlayerExtension.m
- iOS/TCEffectPlayerKit/Classes/TUIExtension/TUIEffectPlayerService.h
- iOS/TCEffectPlayerKit/Classes/TUIExtension/TUIEffectPlayerService.m
- iOS/TCEffectPlayerKit/TCEffectPlayerKit.podspec
adapts to tencent effect player 3.0 SDK
> 【TUILiveKit】【iOS】adapts to tencent effect player 3.0 SDK

- iOS/TCEffectPlayerKit/TCEffectPlayerKit.podspec
bugfix of syntx error of TCEffectPlayerKit.podspec
> 【TUILiveKit】【iOS】bugfix of syntx error of TCEffectPlayerKit.podspec

- iOS/TEBeautyKit/TEBeautyKit.podspec
- iOS/TUILiveKit/Sources/Component/Beauty/BeautyView.swift
【TUILiveKit】【iOS】update advanced beauty
> 【TUILiveKit】【iOS】update advanced beauty

- Android/app/src/main/java/com/trtc/uikit/livekit/example/view/login/LoginActivity.java
- Android/tuilivekit/livekit/src/main/AndroidManifest.xml
- Android/tuilivekit/livekit/src/main/java/com/trtc/uikit/livekit/component/login/LiveKitInitializer.java
> 【TUILiveKit】【Android】LiveKit add TUIRoomEngine auto-login

- Android/tuilivekit/livekit/src/main/java/com/trtc/uikit/livekit/component/audiencelist/AudienceListView.java
- Android/tuilivekit/livekit/src/main/java/com/trtc/uikit/livekit/component/audiencelist/service/AudienceListObserver.java
- Android/tuilivekit/livekit/src/main/java/com/trtc/uikit/livekit/component/audiencelist/store/AudienceListState.java
- Android/tuilivekit/livekit/src/main/java/com/trtc/uikit/livekit/component/audiencelist/view/adapter/AudienceListIconAdapter.java
- Android/tuilivekit/livekit/src/main/res-audience-list/layout/audience_list_layout_icon.xml
audienceList component modify the data pulling strategy
> audienceList component modify the data pulling strategy
